import { ReactNode } from 'react'
import { Inter } from 'next/font/google'
import type { Metadata } from 'next'
import { DefaultSession } from 'next-auth'

import { getAuthSession } from '@/lib/nextauth'
import BasicLayout from './basic-layout'
import './globals.css'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'OpenTyped',
    description: 'Generated by create next app',
}

export default async function RootLayout({ children }: { children: ReactNode }) {
    const session: DefaultSession | null = await getAuthSession();

    console.log(session?.user)

    return (
        <BasicLayout session={session}>
            {children}
        </BasicLayout>
    )
}
