import { ReactNode } from 'react'
import type { Metadata } from 'next'
import { DefaultSession } from 'next-auth'

import { getAuthSession } from '@/lib/nextauth'
import { ThemeProvider } from '@/components/theme/theme-provider'
import { TooltipProvider } from '@/components/ui/tooltip'
import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'
// import BasicLayout from './basic-layout'

import './globals.css'


export const metadata: Metadata = {
    title: 'OpenTyped',
    description: 'Generated by create next app',
}


export default async function RootLayout({ children }: { children: ReactNode }) {
    const session: DefaultSession | null = await getAuthSession();

    // getting user
    console.log(session?.user)


    return (
        // <BasicLayout session={session}>
        //     {children}
        // </BasicLayout>
        <html lang="en" suppressHydrationWarning>
            <body>
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange
                >
                    <TooltipProvider>
                        <Navbar session={session} />
                        {children}
                        <Footer />
                    </TooltipProvider>
                </ThemeProvider>
            </body>
        </html >
    )
}
